{% set name = "opentelemetry-instrumentation-anthropic" %}
{% set version = "0.49.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_anthropic-{{ version }}.tar.gz
  sha256: 7f2180938a5adfc3026689ddec0169b67bca2aa1593d9da9c99a1285df6c0386

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5.0
  run_constrained:
    - anthropic >=0.36.0

# Tests disabled, fixture not found @pytest.mark.vcr -> pytest-vcr -> https://pypi.org/project/pytest-vcr/
test:
  imports:
    - opentelemetry.instrumentation.anthropic
  commands:
    - pip check
  requires:
    - pip
    - anthropic >=0.36.0

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Anthropic instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
