{% set name = "opentelemetry-instrumentation-anthropic" %}
{% set version = "0.40.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_anthropic-{{ version }}.tar.gz
  sha256: 5a7e9b3852cd8cfc43e50450d83d40b1a15d12b295fb18d2c814576072fcc23f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-semantic-conventions-ai 0.4.8
    - typing_extensions
  run_constrained:
    - anthropic >=0.36.0

test:
  imports:
    - opentelemetry.instrumentation.anthropic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - anthropic

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Anthropic instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
