{% set name = "opentelemetry-instrumentation-anthropic" %}
{% set version = "0.47.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_anthropic-{{ version }}.tar.gz
  sha256: 4d77c3bb2b5c10e580b4549a7c1f893c05ef5f909adf0d82f2eb98100597fc3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.12,<0.5
    - typing_extensions
  run_constrained:
    - anthropic >=0.36.0

test:
  imports:
    - opentelemetry.instrumentation.anthropic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - anthropic

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Anthropic instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
