{% set name = "opentelemetry-instrumentation-anthropic" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_anthropic-{{ version }}.tar.gz
  sha256: 169270a3c6b9ce49c3d8c7dbf6e13cea0d20c37938dcbddbf2f30450f596dcc6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0

#AttributeError: module 'opentelemetry.semconv._incubating.attributes.gen_ai_attributes' has no attribute 'GEN_AI_TOOL_DEFINITIONS'
# No module pytest-vcr installed, so we ignore tests that require it.
# Ignored tests:
{% set ignored_tests = [
  "--ignore=tests/test_completion.py",
  "--ignore=tests/test_messages.py",
  "--ignore=tests/test_prompt_caching.py",
  "--ignore=tests/test_thinking.py",
  "--ignore=tests/test_bedrock_with_raw_response.py",
  "--ignore=tests/test_structured_outputs.py",
  "--deselect=tests/test_semconv_span_attrs.py::test_tool_definitions_attribute"
] %}

test:
  imports:
    - opentelemetry.instrumentation.anthropic
  source_files:
    - tests
    - pyproject.toml
  commands:
    - pip check
    - pytest -vvv {{ " ".join(ignored_tests) }}
  requires:
    - pip
    - boto3
    - pytest
    - anthropic
    - pytest-asyncio
    - opentelemetry-sdk

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Anthropic instrumentation
  description: |
    This library allows tracing Anthropic prompts and 
    completions sent with the official Anthropic library.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - timkpaine
